metadata:
        name: mykafka
replicaCount: 2
resources:
        requests:
          memory: 3Gi
          cpu: "2"
        limits:
          memory: 4Gi
          cpu: "3"
storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 15Gi
config:
  insyncReplicas: 2

affinity:
       nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: all-pools-example
                  operator: In
                  values:
                  - "true"

topicname: "topic2"
zookeeper:
        replicaCount: 1
        storage:
          type: persistent-claim
          size: 10Gi

