metadata:
        name: mykafka
replicaCount: 3
resources:
        requests:
          memory: 8Gi
          cpu: "6"
        limits:
          memory: 8Gi
          cpu: "6"
storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
config:
  insyncReplicas: 2

affinity:
       nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: all-pools-example
                  operator: In
                  values:
                  - "true"

topicname: "topic2"
zookeeper:
        replicaCount: 1
        storage:
          type: persistent-claim
          size: 40Gi

